agent.sources        = tail-source
agent.channels       = mem-channel
agent.sinks          = hbase-sink

agent.sources.tail-source.type          = TAILDIR
agent.sources.tail-source.filegroups    = f1
agent.sources.tail-source.filegroups.f1 = /opt/flume/input/user_actions.log
agent.sources.tail-source.positionFile  = /opt/flume/input/taildir_position.json
agent.sources.tail-source.channels      = mem-channel

agent.channels.mem-channel.type               = memory
agent.channels.mem-channel.capacity           = 1000
agent.channels.mem-channel.transactionCapacity= 100


agent.sinks.hbase-sink.type               = hbase
agent.sinks.hbase-sink.table              = user_actions
agent.sinks.hbase-sink.columnFamily       = cf
agent.sinks.hbase-sink.serializer         = com.example.main.JsonEventToHBaseSerializer
agent.sinks.hbase-sink.channel            = mem-channel
